In [1]:
from classes.descriptors import Smiles2Descriptors
import pandas as pd

data

In [7]:
mola = Smiles2Descriptors('CCO')
mola

SMILES: CCO
Descriptors:
  LogP: -0.00
  TPSA: 20.23
  Molecular Weight: 46.07
  Total Bonds: 2
  Rotatable Bonds: 2
  Non-Rotatable Bonds: 0
  Van der Waals Volume: 100.19
  Fraction of non-rotatable bounds: 0.00
  Num atoms: 9
  Degree of branching: 0.0
  Dipole Moment: 1.62 D

In [8]:
input_df = pd.read_csv("data/NTO_smiles_encoded.csv")

In [9]:
def calculate_descriptors(smiles):
    try:
        descriptor = Smiles2Descriptors(smiles)
        return descriptor.as_vector()
    except ValueError as e:
        print(f"Ошибка при обработке {smiles}: {e}")
        return [None] * 6 
    except Exception as e:
        print(f"Неизвестная ошибка для {smiles}: {e}")
        return [None] * 6

In [10]:
descriptor_labels = [
    "LogP",
    "TPSA",
    "MolWt",
    "Van_Der_Waals volume"
    "Fraction_non_rotatable_bounds",
    "num_atoms",
    "Degree_of_branching"
]

In [12]:
descriptors_data = []
for smiles in input_df['smiles']:
    descriptors = calculate_descriptors(smiles)
    descriptors_data.append(descriptors)

[23:01:00] SMILES Parse Error: syntax error while parsing: O=S(C1=CC=C([C18H21])C=C1)(O)=O
[23:01:00] SMILES Parse Error: check for mistakes around position 15:
[23:01:00] O=S(C1=CC=C([C18H21])C=C1)(O)=O
[23:01:00] ~~~~~~~~~~~~~~^
[23:01:00] SMILES Parse Error: Failed parsing SMILES 'O=S(C1=CC=C([C18H21])C=C1)(O)=O' for input: 'O=S(C1=CC=C([C18H21])C=C1)(O)=O'


Ошибка при обработке O=S(C1=CC=C([C18H21])C=C1)(O)=O: Неверный SMILES


[23:01:01] UFFTYPER: Unrecognized atom type: Ca1+2 (13)


Ошибка при обработке CCC(C(OC[CH2](C)CCCCCCC[CH2])=O)C: Неверный SMILES


[23:01:01] Explicit valence for atom # 6 C, 5, is greater than permitted


In [13]:
descriptors_data

[array([2.83260000e+00, 0.00000000e+00, 1.00205000e+02, 2.59868356e+02,
        0.00000000e+00, 2.30000000e+01, 1.42857143e-01, 1.80556106e-02]),
 array([1.00582000e+01, 0.00000000e+00, 3.80745000e+02, 9.60988060e+02,
        0.00000000e+00, 8.30000000e+01, 1.85185185e-01, 6.40083341e-02]),
 array([1.01004000e+01, 0.00000000e+00, 3.66718000e+02, 9.25932075e+02,
        0.00000000e+00, 8.00000000e+01, 7.69230769e-02, 6.60497261e-03]),
 array([9.07420000e+00, 0.00000000e+00, 3.24637000e+02, 8.20764119e+02,
        0.00000000e+00, 7.10000000e+01, 4.34782609e-02, 2.12579585e-02]),
 array([-4.68380000e-01,  1.05500000e+02,  2.82344000e+02,  5.42199622e+02,
         5.00000000e-01,  4.20000000e+01,  1.00000000e-01,  3.51820937e+00]),
 array([3.54610000e+00, 2.63000000e+01, 2.00322000e+02, 4.51868885e+02,
        1.53846154e-01, 3.80000000e+01, 1.42857143e-01, 3.26332434e-01]),
 array([2.83260000e+00, 0.00000000e+00, 1.12216000e+02, 2.80447882e+02,
        7.50000000e-01, 2.40000000e+01, 0.00

In [22]:
target = df_merged['oil_property_value']
target

0          4.52
1          4.52
2          4.52
3          4.52
4          4.52
          ...  
101855    10.09
101856    10.09
101857    10.09
101858    10.09
101859    10.09
Name: oil_property_value, Length: 101860, dtype: float64

first model

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
X_smiles = np.array(descriptors_list)
y_smiles = target_values  # Целевые значения для SMILES
X_train_smiles, X_val_smiles, y_train_smiles, y_val_smiles = train_test_split(X_smiles, y_smiles, test_size=0.2, random_state=42)